// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:ffigen`.
// ignore_for_file: type=lint, unused_import, unused_element, deprecated_member_use_from_same_package
import 'dart:ffi' as ffi;

/// auto generate dll bridge in dart
class JunkFusionDLLBindings {
  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
  _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  JunkFusionDLLBindings(ffi.DynamicLibrary dynamicLibrary)
    : _lookup = dynamicLibrary.lookup;

  /// The symbols are looked up with [lookup].
  JunkFusionDLLBindings.fromLookup(
    ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName) lookup,
  ) : _lookup = lookup;

  void closeBackend() {
    return _closeBackend();
  }

  late final _closeBackendPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function()>>('closeBackend');
  late final _closeBackend = _closeBackendPtr.asFunction<void Function()>();

  void continuePlay() {
    return _continuePlay();
  }

  late final _continuePlayPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function()>>('continuePlay');
  late final _continuePlay = _continuePlayPtr.asFunction<void Function()>();

  void dllInit(
    ffi.Pointer<ffi.Char> cacheDirId,
    ffi.Pointer<ffi.Char> exeDirPtr,
  ) {
    return _dllInit(cacheDirId, exeDirPtr);
  }

  late final _dllInitPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Void Function(ffi.Pointer<ffi.Char>, ffi.Pointer<ffi.Char>)
        >
      >('dllInit');
  late final _dllInit = _dllInitPtr
      .asFunction<
        void Function(ffi.Pointer<ffi.Char>, ffi.Pointer<ffi.Char>)
      >();

  void freeString(ffi.Pointer<ffi.Char> str) {
    return _freeString(str);
  }

  late final _freeStringPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Char>)>>(
        'freeString',
      );
  late final _freeString = _freeStringPtr
      .asFunction<void Function(ffi.Pointer<ffi.Char>)>();

  ffi.Pointer<ffi.Char> getAllSongs() {
    return _getAllSongs();
  }

  late final _getAllSongsPtr =
      _lookup<ffi.NativeFunction<ffi.Pointer<ffi.Char> Function()>>(
        'getAllSongs',
      );
  late final _getAllSongs = _getAllSongsPtr
      .asFunction<ffi.Pointer<ffi.Char> Function()>();

  ffi.Pointer<ffi.Char> getTimeDomainSpecBySongId(int songId) {
    return _getTimeDomainSpecBySongId(songId);
  }

  late final _getTimeDomainSpecBySongIdPtr =
      _lookup<ffi.NativeFunction<ffi.Pointer<ffi.Char> Function(ffi.LongLong)>>(
        'getTimeDomainSpecBySongId',
      );
  late final _getTimeDomainSpecBySongId = _getTimeDomainSpecBySongIdPtr
      .asFunction<ffi.Pointer<ffi.Char> Function(int)>();

  void pausePlay() {
    return _pausePlay();
  }

  late final _pausePlayPtr = _lookup<ffi.NativeFunction<ffi.Void Function()>>(
    'pausePlay',
  );
  late final _pausePlay = _pausePlayPtr.asFunction<void Function()>();

  void playNewSong(int songId) {
    return _playNewSong(songId);
  }

  late final _playNewSongPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Int)>>('playNewSong');
  late final _playNewSong = _playNewSongPtr.asFunction<void Function(int)>();

  void registerCurrentPTSCallback(DoubleFunc doubleFunc) {
    return _registerCurrentPTSCallback(doubleFunc);
  }

  late final _registerCurrentPTSCallbackPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(DoubleFunc)>>(
        'registerCurrentPTSCallback',
      );
  late final _registerCurrentPTSCallback = _registerCurrentPTSCallbackPtr
      .asFunction<void Function(DoubleFunc)>();

  void registerErrorSendCallback(StringFunc cb) {
    return _registerErrorSendCallback(cb);
  }

  late final _registerErrorSendCallbackPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(StringFunc)>>(
        'registerErrorSendCallback',
      );
  late final _registerErrorSendCallback = _registerErrorSendCallbackPtr
      .asFunction<void Function(StringFunc)>();

  void registerTimeDomainSpecInsertOver(StringFunc cb) {
    return _registerTimeDomainSpecInsertOver(cb);
  }

  late final _registerTimeDomainSpecInsertOverPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(StringFunc)>>(
        'registerTimeDomainSpecInsertOver',
      );
  late final _registerTimeDomainSpecInsertOver =
      _registerTimeDomainSpecInsertOverPtr
          .asFunction<void Function(StringFunc)>();

  void saveComment(int songId, ffi.Pointer<ffi.Char> commentText) {
    return _saveComment(songId, commentText);
  }

  late final _saveCommentPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Void Function(ffi.LongLong, ffi.Pointer<ffi.Char>)
        >
      >('saveComment');
  late final _saveComment = _saveCommentPtr
      .asFunction<void Function(int, ffi.Pointer<ffi.Char>)>();

  void seekTargetPTS(double targetSeconds) {
    return _seekTargetPTS(targetSeconds);
  }

  late final _seekTargetPTSPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Double)>>(
        'seekTargetPTS',
      );
  late final _seekTargetPTS = _seekTargetPTSPtr
      .asFunction<void Function(double)>();

  ffi.Pointer<ffi.Char> someImport(ffi.Pointer<ffi.Char> arg0) {
    return _someImport(arg0);
  }

  late final _someImportPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Pointer<ffi.Char> Function(ffi.Pointer<ffi.Char>)
        >
      >('someImport');
  late final _someImport = _someImportPtr
      .asFunction<ffi.Pointer<ffi.Char> Function(ffi.Pointer<ffi.Char>)>();

  int toggleMyLike(int songId) {
    return _toggleMyLike(songId);
  }

  late final _toggleMyLikePtr =
      _lookup<ffi.NativeFunction<ffi.Int Function(ffi.LongLong)>>(
        'toggleMyLike',
      );
  late final _toggleMyLike = _toggleMyLikePtr.asFunction<int Function(int)>();
}

typedef DoubleFunc = ffi.Pointer<ffi.NativeFunction<DoubleFuncFunction>>;
typedef DoubleFuncFunction = ffi.Void Function(ffi.Double);
typedef DartDoubleFuncFunction = void Function(double);
typedef StringFunc = ffi.Pointer<ffi.NativeFunction<StringFuncFunction>>;
typedef StringFuncFunction = ffi.Void Function(ffi.Pointer<ffi.Char> str);
typedef DartStringFuncFunction = void Function(ffi.Pointer<ffi.Char> str);
