// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:ffigen`.
// ignore_for_file: type=lint, unused_import, unused_element, deprecated_member_use_from_same_package
import 'dart:ffi' as ffi;

/// auto generate dll bridge in dart
class JunkFusionDLLBindings {
  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
  _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  JunkFusionDLLBindings(ffi.DynamicLibrary dynamicLibrary)
    : _lookup = dynamicLibrary.lookup;

  /// The symbols are looked up with [lookup].
  JunkFusionDLLBindings.fromLookup(
    ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName) lookup,
  ) : _lookup = lookup;

  void closeBackend() {
    return _closeBackend();
  }

  late final _closeBackendPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function()>>('closeBackend');
  late final _closeBackend = _closeBackendPtr.asFunction<void Function()>();

  void dllInit(
    ffi.Pointer<ffi.Char> cacheDirId,
    ffi.Pointer<ffi.Char> exeDirPtr,
  ) {
    return _dllInit(cacheDirId, exeDirPtr);
  }

  late final _dllInitPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Void Function(ffi.Pointer<ffi.Char>, ffi.Pointer<ffi.Char>)
        >
      >('dllInit');
  late final _dllInit = _dllInitPtr
      .asFunction<
        void Function(ffi.Pointer<ffi.Char>, ffi.Pointer<ffi.Char>)
      >();

  void freeString(ffi.Pointer<ffi.Char> str) {
    return _freeString(str);
  }

  late final _freeStringPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Char>)>>(
        'freeString',
      );
  late final _freeString = _freeStringPtr
      .asFunction<void Function(ffi.Pointer<ffi.Char>)>();

  int getAllSongCount() {
    return _getAllSongCount();
  }

  late final _getAllSongCountPtr =
      _lookup<ffi.NativeFunction<ffi.Int Function()>>('getAllSongCount');
  late final _getAllSongCount = _getAllSongCountPtr
      .asFunction<int Function()>();

  ffi.Pointer<ffi.Char> getAllSongs() {
    return _getAllSongs();
  }

  late final _getAllSongsPtr =
      _lookup<ffi.NativeFunction<ffi.Pointer<ffi.Char> Function()>>(
        'getAllSongs',
      );
  late final _getAllSongs = _getAllSongsPtr
      .asFunction<ffi.Pointer<ffi.Char> Function()>();

  void saveComment(int songId, ffi.Pointer<ffi.Char> commentText) {
    return _saveComment(songId, commentText);
  }

  late final _saveCommentPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Void Function(ffi.LongLong, ffi.Pointer<ffi.Char>)
        >
      >('saveComment');
  late final _saveComment = _saveCommentPtr
      .asFunction<void Function(int, ffi.Pointer<ffi.Char>)>();

  ffi.Pointer<ffi.Char> someImport(ffi.Pointer<ffi.Char> arg0) {
    return _someImport(arg0);
  }

  late final _someImportPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Pointer<ffi.Char> Function(ffi.Pointer<ffi.Char>)
        >
      >('someImport');
  late final _someImport = _someImportPtr
      .asFunction<ffi.Pointer<ffi.Char> Function(ffi.Pointer<ffi.Char>)>();

  int toggleMyLike(int songId) {
    return _toggleMyLike(songId);
  }

  late final _toggleMyLikePtr =
      _lookup<ffi.NativeFunction<ffi.Int Function(ffi.LongLong)>>(
        'toggleMyLike',
      );
  late final _toggleMyLike = _toggleMyLikePtr.asFunction<int Function(int)>();
}
