package_rename_config:
  linux:
    app_name: "Junk Fusion" # (String) The window title of the linux app
    package_name: "com.YusekX.JunkFusion" # (String) The application id of the linux app
    exe_name: "JunkFusion" # (String) The executable name (binary name) of the linux app

  macos:
    app_name: "Junk Fusion" # (String) The product name of the macos app
    package_name: "com.YusekX.JunkFusion" # (String) The product bundle identifier of the macos app
    #copyright_notice: # (String) The product copyright of the macos app

  windows:
    app_name: "Junk Fusion" # (String) The window title & software name of the windows app
    organization: "Junk Fusion" # (String) The organization name (company name) of the windows app
    #copyright_notice: # (String) The legal copyright of the windows app
    exe_name: "JunkFusion" # (String) The executable name (binary name) of the windows app
