name: junk_fusion_ui
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: ^3.12.2

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter
  freezed_annotation: ^3.1.0 # 运行时需要用到的注解
  json_annotation: ^4.12.0 # 👈 新增：用于 JSON 的注解
  # tabler_icons: ^2.5.0+1 #svg图标支持
  tabler_icons_plus: ^3.44.0 #增强版图标
  shared_preferences: ^2.5.0 #和localStorage一样，做轻量数据存储
  ffi: ^2.2.0
  file_picker: ^11.0.3
  # google_fonts: ^8.2.1

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  # cupertino_icons: ^1.0.8

  # Provider — 状态管理库（等价于 Vue 的 Pinia）
  # 用于在 Widget Tree 中注入和访问 ChangeNotifier
  provider: ^6.1.2
  window_manager: ^0.5.2
  logger: ^2.7.0
  path_provider: ^2.1.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.15.1
  freezed: ^3.2.5
  json_serializable: ^6.8.0 # 👈 新增：用于生成 JSON 解析代码
  ffigen: ^21.0.0
  rename_app: ^1.6.6 #用来改变APP名称的依赖包
  flutter_launcher_icons: ^0.14.4 #用来修改应用图标

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^6.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

flutter_launcher_icons:
  image_path: "assets/image/JunkFusion.png"
  windows:
    generate: true
    icon_size: 256
  macos:
    generate: true

flutter:
  assets:
    - assets/image/
  fonts:
    - family: OpenSans
      fonts:
        - asset: assets/fonts/OpenSans-Regular.ttf
          weight: 400
        - asset: assets/fonts/OpenSans-Bold.ttf
          weight: 700

    - family: NotoSansSC
      fonts:
        - asset: assets/fonts/NotoSansSC-Regular.ttf
          weight: 400
        - asset: assets/fonts/NotoSansSC-Bold.ttf
          weight: 700
